### ISSUE TITLE
Works not for all files

### ISSUE THREAD

**Issue by BerndJM** [MLAB-project/stl-thumbnailer#4]
First: it works perfectly even with Nemo / Linux Mint.
But not all files will be thumbnailed. It took me some time of confusion to find the reason for that:
There are stl-files out in the wild with different mime-types:
`model/x.stl-binary` and `model/x.stl-ascii`
So append this mime-types to the `stl.thumbnailer` do get also this files thumbnailed
```
[Thumbnailer Entry]
Exec=/usr/local/bin/stl_thumb.py %i %o %s
MimeType=application/stl;model/x.stl-binary;model/x.stl-ascii
```

**Comment by kaklik** [comment]
Thank very much for the feedback. I have updated the stl.thumbnailer file according to your remark.
